version: "3.6"

services:
  postgres:
    env_file:
      - .env
    image: postgres:11.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        PORT: ${PORT}
        MIX_ENV: ${MIX_ENV}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST: ${POSTGRES_HOST}
        ROOMS_TOKEN: ${ROOMS_TOKEN}
        CLIENT_ID: ${CLIENT_ID}
        CLIENT_SECRET: ${CLIENT_SECRET}
        TENANT_ID: ${TENANT_ID}
        AUTHORIZE_URL: ${AUTHORIZE_URL}
        REDIRECT_URI: ${REDIRECT_URI}
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - static:/app/priv/static

volumes:
  postgres: {}
  static:
    driver_opts:
      device: tmpfs
      type: tmpfs
